display_categories:
  type: list
  default: ""
  description:
    en: A list of categories where the "Board" button should appear. If left blank, it will be shown everywhere. Use @ to denote the top level view.
default_modes:
  type: list
  default: ""
  description:
    en: "Override the default board mode for each category. Use the syntax `category:mode:params`. For example, `support:assigned:david,sam,joffrey`. Use @ to denote the top level view. Use @untagged to display an untagged column."
default_mode_fallback:
  default: ""
  description:
    en: "The default board mode to use when a category is not found in `default_modes`. Use the syntax `mode:params`."
default_view:
  type: list
  default: ""
  description:
    en: A list of categories where the "Board" is the default view. Does not yet support the top level default view. Use `#all` to include all the categories.
default_view_exclude:
  type: "list"
  default: ""
  description:
    en: Exclude categories from the default view. This is useful if you have a default view of all categories (`#all`), but want to exclude one or two.
require_confirmation:
  default: true
  description:
    en: Display a confirmation modal before making changes to a topic's tags/category?
show_tags:
  default: false
  description:
    en: Show tags on topic cards?
num_columns:
  default: 3
  description:
    en: Number of columns to display on screen. More are available by scrolling
